### ISSUE TITLE
search is far too slow

### ISSUE THREAD

**Issue by cwtliu** [Temigo/yuarcuun-web#13]
after adding some .wav files the time it takes to respond to search queries has dramatically increased. I am not sure why this is exactly, I wonder if it's possible to setup the directory in a way where the .wav files are not loaded at all, but only loaded when they are GET requested? I am recording more syllables and planning to compress them so the .wav file size shouldn't be as much of an issue.

I think the fact that it responds so slowly to the backend (even with good wireless internet) means that it would be nearly impossible to load using minimal internet speeds in Alaska. So whatever it takes to make the load more quick is really important! The lag between choosing options in postbase mode seems to be okay for now, though I feel that it is second priority before the search optimization (redux?).

**Comment by Temigo** [comment]
So I agree that the search should be much faster. I am skeptical about the wav files though: it should not be linked to the search time, because .wav are only loaded when the user clicks on the 'listen' button.

**Comment by Temigo** [comment]
@cwtliu did the latest commit  134a967 fix the issue? If yes, we can close it.
