### ISSUE TITLE
retain search when back button is called -- add a delete button 

### ISSUE THREAD

**Issue by cwtliu** [Temigo/yuarcuun-web#15]
Lots of people click the back button after clicking an entry expecting to see the same search results. So how about we have it so that when they use the back button it retains the search? I was thinking that we also move the "Common Words Only" outside the search box and instead have an 'X' delete button, that way people can delete the whole word if they choose (see the screenshot of an example). This would make it easier especially if words are retained when returning to the search.

The "Common Words Only" button could be moved to directly below the search, and perhaps we can have it only display when there are multiple search hits of both common/uncommon. I've been asked many times by people 'what does common words only mean?' before or while they do their search. They end up clicking it and often see no change. It doesn't seem intuitive to have it available as an option if it will not make any immediate changes when pressed, let me know if you agree. so if it's not computationally expensive, (if at least 1 common hit and 1 uncommon hit exists in search ?  show common words only button right below the search button : '') 

![screen shot 2018-10-06 at 1 59 40 pm](https://user-images.githubusercontent.com/28517642/46575776-f47aaa80-c970-11e8-8259-e06cf68a1d1f.png)
![screen shot 2018-10-06 at 2 06 19 pm](https://user-images.githubusercontent.com/28517642/46575779-04928a00-c971-11e8-8f2a-0094b83a477f.png)

**Comment by Temigo** [comment]
The commit  a35dc01 should fix the cancel button issue. I believe everything has been addressed here, please reopen if it is not the case.

**Comment by cwtliu** [comment]
X button is not displaying correctly on Chrome and Safari, need floating right X button instead

**Comment by Temigo** [comment]
Fixed with commit ce6617e07eefd9174ebddbbb68613c450aae8ad1
