### ISSUE TITLE
add disclaimer in yupik entries/front page and next to modified word in postbase mode

### ISSUE THREAD

**Issue by cwtliu** [Temigo/yuarcuun-web#19]
front page
"This website is still being improved. If you notice a mistake, please help out by _reporting the issue_." 

have a ! (error) icon by the modified yupik word in postbase mode (include a link that redirects the this.state information and possibly a snapshot.

Have the link save this.state and have the user submit a small blurb about the issue -> send to a google form or google doc, or whatever is easiest to setup.

**Comment by Temigo** [comment]
Also alert us when  a TTS was requested for a word but does not yet exist

**Comment by cwtliu** [comment]
completed with google form redirect
